all: ui

ui: SettingsDialog.py DeviceInformation.py

SettingsDialog.py:
	pyuic4 ui/SettingsDialog.ui > ui/SettingsDialog.py
	
DeviceInformation.py:
	pyuic4 ui/DeviceInformation.ui > ui/DeviceInformation.py
